### ISSUE TITLE
electron crashed after readBuffer

### ISSUE THREAD

**Issue by symnetry** [Rob--/memoryjs#39] opened 2019-03-08 08:35 UTC
when i call "readBuffer" 
maybe call once or 5-8times
electron turn to whtie page and devtools only left “DevTools was disconnected from the page……”

**Comment by Rob--** [comment] 2019-03-10 18:33
Going to need more information including errors, possibly screenshots etc. With this much information I can't even be sure that `readBuffer` is causing the problems.

**Comment by symnetry** [comment] 2019-03-20 03:57
![1553053778(1)](https://user-images.githubusercontent.com/20887001/54657966-5f2a3780-4b06-11e9-9196-845ce6cfcef4.jpg)

`			memoryjs.openProcess(processName, (error, processObject) => {
				// console.log(error,processObject)
				if(error){
					return message.error("read error")
				}
				let handle = processObject.handle
				let address = parseInt('1008ab4a',16)
				let size = this.state.length
				try{
					// let buffer = memoryjs.readBuffer(handle, address, size);
					// let password=buffer.toString('hex')
					// console.log(password)
					// let form=this.props.form
					// form.setFieldsValue({password})
					// memoryjs.closeProcess(handle)
					memoryjs.readBuffer(handle, address, size,(error,buffer)=>{
						console.log('==\n',`${error} 1=1\n`,buffer)
						memoryjs.closeProcess(handle)
					});
				}catch(err){
					console.log(err)
					fs.appendFile('d:/test.txt', err, function () {
					  console.log('append success');
					});
				}
			})`

crash happen in readBuffer() but have no error message  
never go catch(error) step
those code bind in button click event 
in electron dev mode ,it will call 5-8times then crash
after i packaged for windows this code can read buffer current
but crashed more frequent

**Comment by dw1284** [comment] 2020-06-09 09:05
I am also having this problem. There is no sign of any error messaging anywhere. Its being completely swallowed. I can get away with 1, maybe 2 readbuffer calls, but any more than that and it crashes pretty quickly.

**Comment by Rob--** [comment] 2022-01-26 20:43
It's possible this problem was related to the `readBuffer` memory leak which was fixed in b6b328a.

**Comment by Rob--** [comment] 2022-10-16 15:35
Closing the issue as it's probable the problems here with reading buffers were caused by a memory leak that has now been fixed. Please re-open or create a new issue if you are still having problems reading buffers.

**Closed by Rob--** 2022-10-16 15:35 UTC
