### ISSUE TITLE
DLL Injection

### ISSUE THREAD

**Issue by xetrics** [Rob--/memoryjs#67] opened 2020-08-24 14:54 UTC
Hello, I'd like to help with the implementation of DLL injection. Here is the process:
1. VirtualAllocEx area in the target, where the size of the area is large enough to hold a c string of the full DLL path
2. WriteProcessMemory the full path of the DLL, to the previously allocated memory
3. CreateRemoteThread in the target, where the start routine is LoadLibraryA, with the parameter being the memory location of the dll path.

What step 3 would look like:
```CreateRemoteThread(hProcess, NULL, NULL, (LPTHREAD_START_ROUTINE)GetProcAddress(GetModuleHandleA("Kernel32.dll"), "LoadLibraryA"), remoteString, NULL, NULL);```

4. Free the memory, if you want to be a good boy programmer.

Its actually a really simple progress, should not be hard to implement. I'd love to fork and do it myself, but I have no idea how to work the node bindings.

**Comment by xetrics** [comment] 2020-08-24 15:01
This would already be doable with the current package without adding any aditional c++ code, minus the LoadLibrary call.

**Comment by StiliyanKushev** [comment] 2021-03-13 13:48
I'm looking for a way to tho step 3. I already know how to allocate memory, write the process to the allocated memory, but I'm not sure how to run it. In c++ I just do CreateRemoteThread, but Idk if there's a way using memoryjs.

**Comment by xetrics** [comment] 2021-03-14 16:08
@StiliyanKushev you could try getting the base of the Kernel32 module and use a static offset to CRT.

**Comment by Rob--** [comment] 2021-12-19 06:15
This has been implemented, details in [the other DLL injection issue](https://github.com/Rob--/memoryjs/issues/34#issuecomment-997334240).

Closing as it is a duplicate of #34

**Closed by Rob--** 2021-12-19 06:15 UTC
Labels: duplicate
